#jinja2:lstrip_blocks: True
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'my-project'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'alert.rules'
  # - "first.rules"
  # - "second.rules"

# alert
alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - "alertmanager:9093"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'traefik-ctfd'
    scrape_interval: 5s
    static_configs:
      - targets: ["{{ hostvars['ctfd-server']['private_ip'] }}:8082"]
        labels:
          server_name: ctfd

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
    {% for item in groups['tomonitor'] %}
    - targets: ["{{ hostvars[item]['private_ip'] }}:9101"]
      labels:
        server_name: "{{ item }}"
    {% endfor %}

  - job_name: 'node-exporter'
    scrape_interval: 5s
    static_configs:
    {% for item in groups['tomonitor'] %}
      - targets: ["{{ hostvars[item]['private_ip'] }}:9100"]
        labels:
          server_name: "{{ item }}"
    {% endfor %}