---
# tasks file for cadvisor

- name: cadvisor | create directories
  become: true
  file:
    path: "{{ item }}"
    recurse: true
    state: directory
  with_items:
    - /opt/cadvisor

- name: cadvisor | download
  become: true
  get_url:
    url: "{{ cadvisor_download }}"
    checksum: "sha256:{{ cadvisor_checksum }}"
    dest: "/opt/cadvisor/cadvisor-{{ cadvisor_version }}"
    force: false
    mode: u=rwx,g=rx,o=rx

- name: cadvisor | symlink
  become: true
  file:
    src: "/opt/cadvisor/cadvisor-{{ cadvisor_version }}"
    path: /opt/cadvisor/cadvisor
    force: true
    state: link

- name: cadvisor | server systemd service
  become: true
  template:
    dest: /etc/systemd/system/cadvisor.service
    src: systemd-system-cadvisor-service.j2
  notify:
    - restart cadvisor

- name: cadvisor | enable and start server systemd
  become: true
  systemd:
    enabled: true
    name: cadvisor.service
    state: started
    daemon_reload: true
