---
sudo: required
language: python

services:
  - docker

install:
  - pip install "ome-ansible-molecule<0.5"

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
