server:
  port: 80

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

graphql:
  servlet:
    mapping: /graphql/*
    enabled: true
    corsEnabled: true
    subscriptions:
      websocket:
        path: /subscriptions

graphiql:
  mapping: /graphiql
  enabled: true
  pageTitle: GraphiQL


h2:
  console:
    path: /h2
    enabled: true

---
spring:
  profiles: postgres

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:agenda_db}:${POSTGRES_PORT:5432}/${POSTGRES_DB:postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:secret_agenda_123}
  jpa:
    properties:
      hibernate:
        jdbc:
          lob.non_contextual_creation: true # https://hibernate.atlassian.net/browse/HHH-12368
